### PR TITLE
chore(deps): Update Zeebe deps to 1.0.0

### LINKED ISSUE #100: Update to Zeebe Client 1.0.0
I think that we need to update the zeebe libs to 1.0.0. Why the dependabot is not working?

### PR DESCRIPTION
**Pull request by aivinog1**
I have updated Zeebe deps to 1.0.0. It breaks backward compatibility.

Closes #100

### CODE REVIEW

**Comment by saig0** [comment]
@aivinog1 thank you for contributing :cake: 

I'll enable the build pipeline first and have a look at your changes afterward :rocket:

**Review by saig0 — COMMENTED** [review]
Looks good :+1: 

Please rebase your changes. Then, I can merge the PR :rocket:

**Comment by aivinog1** [comment]
@saig0 Hey, I've rebaised and squashed, can you check this out? :)

**Review by saig0 — APPROVED** [review]
Thanks :tada:

**Pull request merged**
